<?php return array (
  'web' => 
  array (
    'site_id' => '01',
    'site_key' => 'LS201802FORJZDC',
    'jzdc_username' => 'ls_jzdc',
    'jzdc_password' => 'Jzdc@LS',
    'domain' => 'h5.jizhongdiancai.com',
    'name' => '集众电采',
    'title' => '集众电采商城',
    'keywords' => '集众电采商城',
    'description' => '集众电采。家电行业供应链互联网平台。',
    'top_welcome_info' => '您好，集众电采商城 欢迎您',
    'language' => 'chinese_simplified',
    'auto_debug' => false,
    'phone_show_jzdc_bottom' => true,
    'request_geolocation' => false,
    'auth_login_direct_create' => false,
    'weixin_auto_login' => false,
    'search_url' => './index.php?jzdc=mall.goods_list&search=',
    'search_placeholder' => '一键直达家电行业供应链',
    'diy_meta' => '<meta property=&#34;qc:admins&#34; content=&#34;1614134767657601667167&#34; />',
    'wid' => 'gh_fd92a75504d8',
    'authcode_push_mode' => 'sms',
    'other_push_mode' => 'email',
    'circle' => false,
    'login_position' => false,
    'map_api' => 'baidumap',
    'map_secret' => 'CB2ede775afeb6e413abd40261396a69',
    'gps_x' => '0.011',
    'gps_y' => '0.003',
    'img_max' => '10240',
    'share_template' => '我在 {web_name} 发现了 {page_name},快来看看吧',
    'balance_pay_check' => 'none',
  ),
  'openid_notice_template' => 
  array (
    'OPENTM203026900' => 'HFsj2TYbEFxYvX8S4bYpfttdKkoGNbi1FqaTcL5q5OU',
    'OPENTM201673425' => 'h4CagyEofaIszUtohM_VORuIrQ-gJuNoltoh4Zsc_-I',
    'TM00003' => 'NGqt635unFB8esRoCNYcAyQQAdcPhb1h3CibzJD0vG8',
    'TM00335' => 'y1aT7ImNUt5a23PRqtKDwIzvDVSs1OfwqUyaMHl5wEQ',
    'OPENTM205258520' => '-JhAF6VXQ2f-OrNZZUVYhzkzoSefkTt47ujNCn0WI1c',
    'TM00891' => 'Zy4RBgn2tLCsvDIT7blGm2B-P0cYVEUDswDjcYux4eI',
    'OPENTM207112032' => '7upqdth5FSwc_CdMPcvuOWU0ihie74I3jn6HvU9-Vn0',
    'OPENTM204690186' => 'Vz2kpLJQAIpmfvHIao9A6tyDhOiMln0nTL_DI_N9udg',
    'OPENTM200565259' => '3P_znkltdF2GpawPuk3TdRNljSe_Vv9duXPGltlBnEo',
    'OPENTM200750297' => '1tSpIzInfEhb-1zN2hKUlKUdXRJ1ZkG173vAZnnzUcY',
    'OPENTM201490123' => '-l6mkrG8LQMSB6rbM3e04SI6UX9mxj9nlXrtkoVgWCM',
    'OPENTM204146731' => 'hBLHrm8x8gG9t4NNQNheTuJfieDZgqpq8d_MvjoWRIQ',
    'OPENTM202849987' => 'F51Qzi5XzQAk2S_WyViaXmujVfLT6DJDfDlkT9EeIyE',
    'OPENTM202119578' => 'vbvSK1AdReqYl7rS8KyqV7hzAF-odOjE-JdaBtgtWok',
  ),
  'reg_set' => 
  array (
    'phone_country' => '86',
    'phone' => true,
    'email' => false,
    'check' => 'phone',
    'user_agreement_url' => './index.php?jzdc=diypage.show&id=123',
    'default_group_id' => '6',
  ),
  'credits_set' => 
  array (
    'rate' => '0.01',
    'login' => '1',
    'share' => '2',
    'introduce' => 100,
  ),
  'cache' => 
  array (
    'sql_cache_switch' => true,
    'cache_switch' => false,
    'cache_time' => 60,
    'cache_type' => 'file',
    'memcache_host' => 'localhost',
    'memcache_port' => 11211,
  ),
  'upload' => 
  array (
    'upAllowSuffix' => 'jpg,png,gif,zip,rar,apk,htm,gzip,ttf,sql,ico,html,ptxt,php,3gp,rm,rmvb,wmv,avi,mpg,mpeg,mp4,mov,mp3,wma,wav,amr,mp4,txt,jpeg,csv',
    'sys_upload_max_filesize' => 33554432,
    'sys_post_max_size' => 33554432,
  ),
  'server' => 
  array (
    'os_charset' => 'gbk',
  ),
  'withdraw_set' => 
  array (
    'before_mode' => true,
    'rate' => '1',
    'wx_withdraw_auto_pay' => '100',
    'min' => '10',
    'remark' => '平台财务每周二下午批量打款，请周三上午查收',
    'max_time' => '100',
  ),
  'sms' => 
  array (
    'apikey' => '11236d9bf0fe6a5bcc36adb74e47bf1c',
    'validation_template' => '【集众电采】您的验证码是#code#。如非本人操作，请忽略本短信',
    'validation_template_en' => '【集众电采】Your verification code is #code#',
    'fail_email' => 'wushwu@qq.com',
    'frequency_limit' => '1:1/3:2/5:3/10:6/30:10/60:15/1440:20/10080:30/43200:60',
    'cert_suc' => '2274788',
    'cert_submit' => '2274784',
    'cert_fail' => '2274794',
    'order_cancel'=> '2274878',
    'order_pending_send'=> '2274796',
    'order_send1'=> '2274856',
    'order_send2'=> '2275804',
    'order_supplier_confirm'=> '2274868',
    'order_out_date'=> '2274858',

  ),
  'unlogin_function_power' => 
  array (
    0 => 'index.head',
    1 => 'index.top_bar',
    2 => 'index.user_position',
    3 => 'index.visitor_position',
    4 => 'index.login',
    5 => 'index.resetPassword',
    6 => 'index.reg_user',
    7 => 'index.diy_phone_home_page',
    8 => 'index.navigation',
    9 => 'index.foot',
    10 => 'diypage.show',
    12 => 'index.closed',
    13 => 'server.program_market',
    14 => 'server.program_detail',
    15 => 'server.program_screenshot',
    16 => 'server.program_server',
    17 => 'server.template_market',
    18 => 'server.template_detail',
    19 => 'server.template_screenshot',
    20 => 'server.template_server',
    21 => 'index.device',
    22 => 'index.robot',
    23 => 'index.not_found',
    24 => 'index.customer_service',
    25 => 'slider.show',
    26 => 'diypage.show_content',
    27 => 'diypage.show_list',
    28 => 'image.show',
    29 => 'image.show_content',
    30 => 'image.show_list',
    31 => 'image.show_thumb',
    32 => 'image.show_type',
    33 => 'diypage.show_type',
    34 => 'diypage.show_page_list',
    35 => 'article.show',
    36 => 'article.show_list',
    37 => 'article.show_type',
    38 => 'article.show_article_list',
    39 => 'feedback.add',
    40 => 'feedback.list',
    41 => 'form.data_add',
    42 => 'form.data_show_list',
    43 => 'form.data_show_detail',
    44 => 'diymodule.show',
    45 => 'server.send_sms',
    46 => 'server.inquiry_sms',
    49 => 'index.debug',
    53 => 'talk.type',
    54 => 'talk.title',
    55 => 'talk.content',
    56 => 'talk.type_module',
    57 => 'talk.title_module',
    61 => 'travel.line_detail',
    65 => 'copy.task',
    90 => 'diypage.foot_six_grid',
    91 => 'shop.type_module_two',
    92 => 'menu.module',
    108 => 'image.type_list',
    109 => 'image.type_module',
    110 => 'mall.show_type',
    111 => 'mall.show_type_module',
    112 => 'mall.type_module_left',
    113 => 'mall.goods_list',
    114 => 'mall.goods',
    115 => 'mall.search',
    116 => 'mall.cart',
    117 => 'mall.goods_module',
    118 => 'mall.my_cart',
    119 => 'mall.package',
    120 => 'mall.confirm_order',
    121 => 'mall.receiver_add',
    122 => 'mall.receiver_edit',
    123 => 'mall.pay',
    124 => 'mall.auto_print',
    125 => 'mall.checkout_pay',
    126 => 'mall.catalog',
    127 => 'mall.shop_list',
    128 => 'mall.shop',
    129 => 'mall.shop_goods_type',
    130 => 'mall.shop_goods_list',
    131 => 'mall.shop_diypage',
    132 => 'mall.apply_shop',
    133 => 'mall.shop_goods_type_module',
    134 => 'mall.shop_goods_list_module',
    135 => 'mall.shop_diymodule',
    136 => 'mall.index',
    137 => 'mall.shop_index',
    138 => 'mall.layout',
    139 => 'mall.diypage_show',
    140 => 'mall.type_module_two',
    141 => 'mall.shop_name',
    142 => 'mall.shop_search',
    143 => 'mall.goods_snapshot',
    144 => 'mall.auto_receipt_expire_order',
    148 => 'ci.show_type',
    149 => 'ci.show_type_module',
    150 => 'ci.type_module_left',
    151 => 'ci.type_module_two',
    152 => 'ci.list',
    153 => 'ci.detail',
    154 => 'ci.add_option_type',
    155 => 'ci.add',
    156 => 'ci.edit',
    157 => 'ci.list_module',
    158 => 'ci.search',
    159 => 'index.oauth_bind_option',
    160 => 'index.phone_bottom',
    161 => 'image.product',
    162 => 'agency.shop',
    163 => 'agency.spread',
    164 => 'pk.show',
    165 => 'index.circle',
    166 => 'index.circle_module',
    167 => 'mall.interest_goods',
    168 => 'mall.interest_goods_list',
    169 => 'mall.shop_map',
    171 => 'axis.show',
    172 => 'mall.shop_module',
    173 => 'mall.brand_module',
    174 => 'best.show',
    175 => 'credit.use',
    176 => 'weixin.index',
    177 => 'mall.type_goods',
    178 => 'im.use',
  ),
  'image_mark' => 
  array (
    'type' => 'logo',
    'position' => 9,
    'opacity' => 50,
    'water_logo' => 'image_mark.png',
    'color' => '102,255,0',
    'font_size' => 38,
    'font_angle' => -45,
    'ttf_path' => '',
  ),
  'other' => 
  array (
    'reg_phone' => '/[0-9]{5,12}$/',
    'user_login_log' => 100,
    'date_style' => 'Y-m-d',
    'timeoffset' => '8',
    'optional_year_range' => '1930-2030',
    'export_csv_charset' => 'gbk',
  ),
  '' => '',
  'program' => 
  array (
    'language' => 'chinese_simplified',
    'cache_time' => 8,
    'template' => 'default',
    'imageMark' => true,
    'state' => 'opening',
  ),
  'class_name' => 'index',
  'no_update' => 
  array (
    'jzdc_version' => '4.0',
  ),
  'phone_country_reg' => 
  array (
    86 => '/^1[0-9]{10}$/',
  ),
)?>